// Build-time article loader. Runs only in server components / at build under
// `output: "export"`, so none of these markdown deps reach the client bundle.
// (Uses node:fs, so it can never be bundled into a client component anyway.)
import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import readingTime from "reading-time";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkRehype from "remark-rehype";
import rehypeRaw from "rehype-raw";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import rehypePrettyCode from "rehype-pretty-code";
import rehypeStringify from "rehype-stringify";
import { visit } from "unist-util-visit";
import type { Root, Element, ElementContent } from "hast";

import { withBasePath } from "./base-path";

const ARTICLES_DIR = path.join(process.cwd(), "content", "articles");

export type ArticleMeta = {
    slug: string;
    title: string;
    description: string;
    category: string;
    /** ISO date string (YYYY-MM-DD) the article was written on. */
    date: string;
    /** File name under public/articles/, e.g. "foo.png". */
    coverImage: string;
    keywords: string[];
    readingMinutes: number;
    wordCount: number;
};

export type ArticleHeading = {
    /** Anchor id generated by rehype-slug. */
    id: string;
    text: string;
    depth: 2 | 3;
};

export type Article = {
    meta: ArticleMeta;
    /** Pre-rendered, syntax-highlighted HTML body. */
    html: string;
    /** h2/h3 headings in document order, for the table of contents. */
    headings: ArticleHeading[];
};

function elementText(node: Element): string {
    let text = "";
    for (const child of node.children) {
        if (child.type === "text") text += child.value;
        else if (child.type === "element") text += elementText(child);
    }
    return text;
}

function hasClass(el: Element, name: string): boolean {
    const cls = el.properties?.className;
    return Array.isArray(cls) && cls.includes(name);
}

/** Prepend a header row (language label + copy button) to a rehype-pretty-code figure. */
function addCodeHeader(figure: Element) {
    const pre = figure.children.find(
        (child): child is Element => child.type === "element" && child.tagName === "pre"
    );
    if (!pre) return;

    // rehype-pretty-code stores data attributes under raw kebab-case keys.
    const language = pre.properties?.dataLanguage ?? pre.properties?.["data-language"];
    const header: Element = {
        type: "element",
        tagName: "div",
        properties: { className: ["code-header"] },
        children: [
            {
                type: "element",
                tagName: "span",
                properties: { className: ["code-lang"] },
                children:
                    typeof language === "string" && language !== "plaintext"
                        ? [{ type: "text", value: language }]
                        : [],
            },
            {
                type: "element",
                tagName: "button",
                properties: { type: "button", className: ["code-copy"], ariaLabel: "Copy code to clipboard" },
                children: [{ type: "text", value: "COPY" }],
            },
        ],
    };
    figure.children.splice(figure.children.indexOf(pre), 0, header);
}

/**
 * Build-time HTML post-processing:
 * - collects h2/h3 headings for the table of contents
 * - prefixes root-relative <img src> with the basePath and lazy-loads prose images
 * - opens external links in a new tab
 * - wraps tables so they can scroll horizontally on small screens
 * - prepends a language label + copy button to code block figures
 */
function rehypeArticleExtras(headings: ArticleHeading[]) {
    return (tree: Root) => {
        visit(tree, "element", (node, index, parent) => {
            if ((node.tagName === "h2" || node.tagName === "h3") && typeof node.properties?.id === "string") {
                headings.push({
                    id: node.properties.id,
                    text: elementText(node),
                    depth: node.tagName === "h2" ? 2 : 3,
                });
                return;
            }
            if (node.tagName === "img") {
                if (typeof node.properties?.src === "string") {
                    node.properties.src = withBasePath(node.properties.src);
                }
                node.properties = { ...node.properties, loading: "lazy", decoding: "async" };
                return;
            }
            if (
                node.tagName === "a" &&
                typeof node.properties?.href === "string" &&
                /^https?:\/\//.test(node.properties.href)
            ) {
                node.properties.target = "_blank";
                node.properties.rel = ["noopener", "noreferrer"];
                return;
            }
            if (
                node.tagName === "table" &&
                parent &&
                typeof index === "number" &&
                !(parent.type === "element" && hasClass(parent, "table-wrap"))
            ) {
                const wrapper: Element = {
                    type: "element",
                    tagName: "div",
                    properties: { className: ["table-wrap"] },
                    children: [node],
                };
                (parent.children as ElementContent[])[index] = wrapper;
                return;
            }
            if (
                node.tagName === "figure" &&
                node.properties &&
                ("dataRehypePrettyCodeFigure" in node.properties ||
                    "data-rehype-pretty-code-figure" in node.properties)
            ) {
                addCodeHeader(node);
            }
        });
    };
}

function fileToSlug(fileName: string): string {
    return fileName.replace(/\.md$/, "");
}

function readArticleFile(slug: string): { data: matter.GrayMatterFile<string>["data"]; content: string } {
    const fullPath = path.join(ARTICLES_DIR, `${slug}.md`);
    const raw = fs.readFileSync(fullPath, "utf8");
    const { data, content } = matter(raw);
    return { data, content };
}

function toMeta(slug: string, data: Record<string, unknown>, content: string): ArticleMeta {
    const keywords = Array.isArray(data.keywords) ? (data.keywords as string[]) : [];
    const stats = readingTime(content);
    const readingMinutes =
        typeof data.readingMinutes === "number"
            ? data.readingMinutes
            : Math.max(1, Math.round(stats.minutes));

    return {
        slug,
        title: String(data.title ?? slug),
        description: String(data.description ?? ""),
        category: String(data.category ?? "Uncategorized"),
        date: String(data.date ?? ""),
        coverImage: String(data.coverImage ?? ""),
        keywords,
        readingMinutes,
        wordCount: stats.words,
    };
}

let cachedMetas: ArticleMeta[] | null = null;

/** All articles, newest first. Cached for the lifetime of the build. */
export function getAllArticles(): ArticleMeta[] {
    if (cachedMetas) return cachedMetas;

    if (!fs.existsSync(ARTICLES_DIR)) {
        cachedMetas = [];
        return cachedMetas;
    }

    const metas = fs
        .readdirSync(ARTICLES_DIR)
        .filter((file) => file.endsWith(".md"))
        .map((file) => {
            const slug = fileToSlug(file);
            const { data, content } = readArticleFile(slug);
            return toMeta(slug, data, content);
        })
        .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));

    cachedMetas = metas;
    return metas;
}

export function getAllSlugs(): string[] {
    return getAllArticles().map((a) => a.slug);
}

/** Distinct categories in first-seen (chronological) order. */
export function getAllCategories(): string[] {
    const seen = new Set<string>();
    for (const article of getAllArticles()) seen.add(article.category);
    return [...seen];
}

export async function getArticleBySlug(slug: string): Promise<Article | null> {
    const fullPath = path.join(ARTICLES_DIR, `${slug}.md`);
    if (!fs.existsSync(fullPath)) return null;

    const { data, content } = readArticleFile(slug);
    const meta = toMeta(slug, data, content);
    const headings: ArticleHeading[] = [];

    const file = await unified()
        .use(remarkParse)
        .use(remarkGfm)
        .use(remarkRehype, { allowDangerousHtml: true })
        .use(rehypeRaw)
        .use(rehypeSlug)
        .use(rehypeAutolinkHeadings, { behavior: "wrap" })
        .use(rehypePrettyCode, {
            theme: "github-dark-dimmed",
            keepBackground: false,
        })
        .use(rehypeArticleExtras, headings)
        .use(rehypeStringify, { allowDangerousHtml: true })
        .process(content);

    return { meta, html: String(file), headings };
}
